import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const playwright=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browserName=process.env.QA_BROWSER||'chromium';
const browser=await playwright[browserName].launch({headless:true,...(browserName==='chromium'&&process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const base=process.env.QA_URL||'http://127.0.0.1:4187/';
const out=process.env.QA_OUTPUT||'qa/reservations';
const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Tokyo'});
const page=await context.newPage();
const results=[];const errors=[];
page.on('pageerror',e=>errors.push(e.message));
const check=(name,value)=>{assert.ok(value,name);results.push(name);};
await mkdir(out,{recursive:true});
try{
  // It is September 13 in Tokyo and UTC, but still September 12 in Venezuela.
  await page.clock.install({time:new Date('2026-09-13T01:30:00Z')});
  await page.goto(base);
  await page.locator('.mobile-dock [data-open="reservation"]').click();
  check('Minimum date follows Venezuela, not the visitor time zone',await page.locator('#rDate').getAttribute('min')==='2026-09-12');
  await page.locator('#rDate').fill('2026-09-12');await page.locator('#rTime').fill('20:00');
  await page.locator('#rPeople').fill('2');await page.locator('#rName').fill('<img src=x onerror=alert(1)>');await page.locator('#rPhone').fill('+58 400 000 0000');
  await page.locator('#reservationForm button[type="submit"]').click();
  check('A past time today is rejected in Venezuela',/hora futura/.test(await page.locator('#reservationError').innerText()));
  await page.locator('#rTime').fill('22:00');await page.locator('#reservationForm button[type="submit"]').click();
  check('A later time today is accepted',await page.locator('#confirmReservation').isVisible());
  await page.locator('#confirmReservation').click();
  check('Receipt safely renders a name as text',await page.locator('#confirmBody img').count()===0 && (await page.locator('#confirmBody').innerText()).includes('<img'));
  await page.screenshot({path:`${out}/receipt-mobile.png`,animations:'disabled'});
  await page.keyboard.press('Escape');await page.locator('.mobile-dock [data-open="reservation"]').click();
  check('Closing and reopening retains the demo booking',await page.locator('#modifyReservation').isVisible());
  await page.locator('#modifyReservation').click();await page.locator('#rDate').fill('2026-09-13');await page.locator('#rTime').fill('00:15');await page.locator('#reservationForm button[type="submit"]').click();
  check('A next-day early time is accepted',await page.locator('#confirmReservation').isVisible());
  await page.locator('#confirmReservation').click();await page.locator('#viewReservation').click();
  await page.screenshot({path:`${out}/manage-mobile.png`,animations:'disabled'});
  await page.locator('#cancelReservation').click();await page.keyboard.press('Escape');await page.locator('.mobile-dock [data-open="reservation"]').click();
  check('Cancellation remains visible after reopening',await page.locator('.reservation-status.cancelled').isVisible());
  check('Reservation details are not saved in browser storage',await page.evaluate(()=>!JSON.stringify({...localStorage,...sessionStorage}).includes('onerror')));
  await page.reload();await page.locator('.mobile-dock [data-open="reservation"]').click();
  check('Reload resets the in-memory reservation',await page.locator('#rName').inputValue()==='' && await page.locator('#modifyReservation').count()===0);
  check('No browser errors',errors.length===0);
  await writeFile(`${out}/report.json`,JSON.stringify({status:'pass',browser:browserName,base,checks:results.length,results,errors},null,2));
  console.log(JSON.stringify({status:'pass',checks:results.length,browser:browserName}));
}finally{await browser.close()}
